AWSTemplateFormatVersion: '2010-09-09'
Description: 'Exhibition Crawler Automation using AWS Batch and EventBridge'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select VPC ID
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs

Resources:
  # ECR Repository
  ExhibitionCrawlerRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: exhibition-crawler
      ImageScanningConfiguration:
        ScanOnPush: true

  # IAM Roles
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  # Batch Compute Environment
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        DesiredvCpus: 0
        MaxvCpus: 4
        InstanceTypes: 
          - optimal
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        InstanceRole: !GetAtt IamInstanceProfile.Arn
      ServiceRole: !GetAtt BatchServiceRole.Arn
      State: ENABLED

  # Security Group
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Batch compute environment
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  # Batch Job Queue
  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      Priority: 1
      State: ENABLED
      JobQueueName: exhibition-crawler-queue
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment

  # Batch Job Definition
  CrawlerJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      ContainerProperties:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ExhibitionCrawlerRepo}:latest
        Vcpus: 1
        Memory: 2048
      RetryStrategy:
        Attempts: 2

  # EventBridge Rule
  CrawlerScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Run exhibition crawler every Monday at 9 AM KST"
      ScheduleExpression: "cron(0 0 ? * MON *)"
      State: ENABLED
      Targets:
        - Arn: !Sub arn:aws:batch:${AWS::Region}:${AWS::AccountId}:job-queue/exhibition-crawler-queue
          Id: CrawlerBatchTarget
          RoleArn: !GetAtt EventBridgeRole.Arn
          BatchParameters:
            JobDefinition: !Ref CrawlerJobDefinition
            JobName: exhibition-crawler-job

  # EventBridge IAM Role
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BatchSubmitPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: batch:SubmitJob
                Resource:
                  - !Ref CrawlerJobDefinition
                  - !Ref BatchJobQueue

  # IAM Instance Profile
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles: 
        - !Ref BatchInstanceRole

Outputs:
  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ExhibitionCrawlerRepo} 